-- ============================================================
-- FreshBox: Initial Schema Migration
-- Created: 2026-02-28
-- Description: Core tables for the mini e-commerce platform
-- ============================================================

-- ---- Enum for order status ----
CREATE TYPE public.order_status AS ENUM ('new', 'processing', 'done', 'cancelled');

-- ============================================================
-- 1) profiles – user profile linked to auth.users
-- ============================================================
CREATE TABLE public.profiles (
  id          uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  full_name   text,
  phone       text,
  address     text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 2) user_roles – role assignment (user / admin)
-- ============================================================
CREATE TABLE public.user_roles (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  role        text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

CREATE INDEX idx_user_roles_user_id ON public.user_roles (user_id);

-- ============================================================
-- 3) categories – product categories
-- ============================================================
CREATE TABLE public.categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  description text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 4) products – belongs to a category, has image_path
-- ============================================================
CREATE TABLE public.products (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id   bigint REFERENCES public.categories (id) ON DELETE SET NULL,
  name          text NOT NULL,
  description   text,
  price         numeric(10, 2) NOT NULL CHECK (price >= 0),
  unit          text NOT NULL DEFAULT 'кг',
  image_path    text,
  in_stock      boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_category_id ON public.products (category_id);

-- ============================================================
-- 5) orders – belongs to a user, has status
-- ============================================================
CREATE TABLE public.orders (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  status        public.order_status NOT NULL DEFAULT 'new',
  total_amount  numeric(10, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  note          text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_user_id ON public.orders (user_id);

-- ============================================================
-- 6) order_items – belongs to order + product
-- ============================================================
CREATE TABLE public.order_items (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      bigint NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
  product_id    bigint REFERENCES public.products (id) ON DELETE SET NULL,
  quantity      integer NOT NULL CHECK (quantity > 0),
  unit_price    numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_items_order_id  ON public.order_items (order_id);
CREATE INDEX idx_order_items_product_id ON public.order_items (product_id);
